apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.deployment.bdd.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.bdd.labels }}
  serviceName: "bdd-gestion"
  replicas: {{ .Values.deployment.bdd.replicasCount }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.bdd.labels }}
    spec:
      containers:
      - name: bdd-depense
        image: postgres:17-alpine
        resources:
          requests:
            cpu: 20m
            memory: 120Mi
          limits:
            cpu: 80m
            memory: 180Mi
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: {{ .Values.configmap.bdd.name }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
        - "ReadWriteOnce"
      storageClassName: local-path
      resources:
        requests:
          storage: 300Mi