apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-svc
  name: {{ .Values.service.backend.name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.backend.ports }}
    targetPort: {{ .Values.service.backend.targetPort }}
  selector:
    app: {{ .Values.deployment.backend.labels }}
  type: {{ .Values.service.backend.type }}
status:
  loadBalancer: {}
