apiVersion: v1
kind: Service
metadata:
  labels:
    app: depense-bdd
  name: {{ .Values.deployment.bdd.name }}
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: {{ .Values.deployment.bdd.labels }}
  type: {{ .Values.deployment.bdd.type }}
status:
  loadBalancer: {}